# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-29 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=240)),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
